version: '3'
services:
  server:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:  
      - 3900:3900

  client:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 80:80